# frozen_string_literal: true

ActiveRecord::Base.transaction do
  puts "-- Creating cardsets"

  easy_difficulty = Cardset.find_by!(name: "Easy difficulty")
  moderate_difficulty = Cardset.find_by!(name: "Moderate difficulty")
  hard_difficulty = Cardset.find_by!(name: "Hard difficulty")

  general_knowledge = Category.find_by!(name: "General Knowledge")
  entertainment_books = Category.find_by!(name: "Entertainment: Books")
  entertainment_film = Category.find_by!(name: "Entertainment: Film")
  entertainment_music = Category.find_by!(name: "Entertainment: Music")
  entertainment_television = Category.find_by!(name: "Entertainment: Television")
  science_nature = Category.find_by!(name: "Science & Nature")
  mythology = Category.find_by!(name: "Mythology")
  sports = Category.find_by!(name: "Sports")
  geography = Category.find_by!(name: "Geography")
  history = Category.find_by!(name: "History")
  politics = Category.find_by!(name: "Politics")
  animals = Category.find_by!(name: "Animals")
  vehicles = Category.find_by!(name: "Vehicles")

  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What is the first book of the Old Testament?", answer: "Genesis")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What was the first ever London Underground line to be built?", answer: "Metropolitan Line")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What is Tasmania?", answer: "An Australian State")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "In which fast food chain can you order a Jamocha Shake?", answer: "Arby's")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What zodiac sign is represented by a pair of scales?", answer: "Libra")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What nuts are used in the production of marzipan?", answer: "Almonds")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What is Cynophobia the fear of?", answer: "Dogs")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "If you are caught \"Goldbricking\", what are you doing wrong?", answer: "Slacking")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "What are Panama hats made out of?", answer: "Straw")
  Card.find_or_create_by!(category: general_knowledge, cardset: easy_difficulty, question: "Foie gras is a French delicacy typically made from what part of a duck or goose?", answer: "Liver")

  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "George Orwell wrote this book, which is often considered a statement on government oversight.", answer: "1984")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "What was the name of Captain Nemo's submarine in \"20,000 Leagues Under the Sea\"?", answer: "The Nautilus")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "Who wrote the novel 'Fear And Loathing In Las Vegas'?", answer: "Hunter S. Thompson")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "Which famous spy novelist wrote the childrens' story \"Chitty-Chitty-Bang-Bang\"?", answer: "Ian Fleming")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "How many Harry Potter books are there?", answer: "7")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "What's Harry Potter's dad's name?", answer: "James Potter")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "Who wrote the young adult novel \"The Fault in Our Stars\"?", answer: "John Green")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "Who was the author of the 1954 novel, \"Lord of the Flies\"?", answer: "William Golding")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "What was the first ever entry written for the SCP Foundation collaborative writing project?", answer: "SCP-173")
  Card.find_or_create_by!(category: entertainment_books, cardset: easy_difficulty, question: "Who wrote \"A Tale of Two Cities\"?", answer: "Charles Dickens")

  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "Which of the following movies was not based on a novel by Stephen King? ", answer: "The Thing")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "Who starred as Bruce Wayne and Batman in Tim Burton's 1989 movie \"Batman\"?", answer: "Michael Keaton")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "Which animated movie was first to feature a celebrity as a voice actor?", answer: "Aladdin")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "Who played Deputy Marshal Samuel Gerard in the 1993 film \"The Fugitive\"?", answer: "Tommy Lee Jones")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "When does \"Rogue One: A Star Wars Story\" take place chronologically in the series?", answer: "Between Episode 3 and 4")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "\"The first rule is: you don't talk about it\" is a reference to which movie?", answer: "Fight Club")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "At the end of the 2001 film \"Rat Race\", whose concert do the contestants crash?", answer: "Smash Mouth")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "Who plays the character of Po in the Kung Fu Panda movies?", answer: "Jack Black")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "The 2016 Disney animated film 'Moana' is based on which culture?", answer: "Polynesian")
  Card.find_or_create_by!(category: entertainment_film, cardset: easy_difficulty, question: "The 1996 film 'Fargo' is primarily set in which US state?", answer: "Minnesota")

  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "Which famous rapper is featured in Jack &Uuml; (Skrillex and Diplo)'s 2015 single called \"Febreze\"?", answer: "2 Chainz")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "Which artist released the 2012 single \"Harlem Shake\", which was used in numerous YouTube videos in 2013?", answer: "Baauer")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "Brian May was the guitarist for which band?", answer: "Queen")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "The \"K\" in \"K-Pop\" stands for which word?", answer: "Korean")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "Which band released songs suchs as \"Rio\", \"Girls on Film\", and \"The Reflex\"?", answer: "Duran Duran")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "Kanye West at 2009 VMA's interrupted which celebrity?", answer: "Taylor Swift")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "According to the American rapper Nelly, what should you do when its hot in here?", answer: "Take off all your clothes")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "When was Gangnam Style uploaded to YouTube?", answer: "2012")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "The band Muse released their first album, Showbiz, in what year?", answer: "1999")
  Card.find_or_create_by!(category: entertainment_music, cardset: easy_difficulty, question: "\"Hallelujah\" is a song written by which Canadian recording artist?", answer: "Leonard Cohen")

  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In the TV show \"Cheers\", Sam Malone was a former relief pitcher for which baseball team?", answer: "Boston Red Sox")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In the TV show 'M*A*S*H', what was the nickname of Corporal Walter O'Reilly?", answer: "Radar")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In the original Star Trek TV series, what was Captain James T. Kirk's middle name?", answer: "Tiberius")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "Grant Gustin plays which superhero on the CW show of the same name?", answer: "The Flash")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In which British seaside town was the BBC sitcom \"Fawlty Towers\" set?", answer: "Torquay")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In Supernatural, what's is Sam's brothers name?", answer: "Dean")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "What is the real name of the famous spanish humorist, El Risitas?", answer: "Juan Joya Borga")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "What is the name of the planet that the Doctor from television series \"Doctor Who\" comes from?", answer: "Gallifrey")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In the TV show \"Mad Men\", what was Donald Draper's birthname?", answer: "Richard \"Dick\" Whitman")
  Card.find_or_create_by!(category: entertainment_television, cardset: easy_difficulty, question: "In AMC's TV Series \"The Walking Dead\" what are \"Zombies\" referred to as?", answer: "Walkers")

  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "Which Apollo mission was the first one to land on the Moon?", answer: "Apollo 11")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "What does the letter 'S' stand for in 'NASA'?", answer: "Space")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "What name is given to all baby marsupials?", answer: "Joey")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "Rhinoplasty is a surgical procedure on what part of the human body?", answer: "Nose")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "What is the powerhouse of the cell?", answer: "Mitochondria")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "What does DNA stand for?", answer: "Deoxyribonucleic Acid")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "Human cells typically have how many copies of each gene?", answer: "2")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "What animal takes part in Schr&ouml;dinger's most famous thought experiment?", answer: "Cat")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "What lies at the center of our galaxy?", answer: "A black hole")
  Card.find_or_create_by!(category: science_nature, cardset: easy_difficulty, question: "Dry ice is the solid form of what substance?", answer: "Carbon dioxide")

  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "Who was the only god from Greece who did not get a name change in Rome?", answer: "Apollo")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "Who in Greek mythology, who led the Argonauts in search of the Golden Fleece?", answer: "Jason")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "This Greek goddess's name was chosen for the dwarf planet responsible for discord on Pluto's classification amongst astronomers.", answer: "Eris")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "The greek god Poseidon was the god of what?", answer: "The Sea")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "Which figure from Greek mythology traveled to the underworld to return his wife Eurydice to the land of the living?", answer: "Orpheus")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "In most traditions, who was the wife of Zeus?", answer: "Hera")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "Which of these mythological creatures is said to be half-man and half-horse?", answer: "Centaur")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "What mythology did the god \"Apollo\" come from?", answer: "Greek and Roman")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "What mytological creatures have women's faces and vultures' bodies?", answer: "Harpies")
  Card.find_or_create_by!(category: mythology, cardset: easy_difficulty, question: "The Nike apparel and footwear brand takes it's name from the Greek goddess of what?", answer: "Victory")

  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "In golf, what name is given to a hole score of two under par?", answer: "Eagle")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "How many soccer players should be on the field at the same time?", answer: "22")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "Which country is hosting the 2018 FIFA World Cup?", answer: "Russia")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "Which city did the former NHL team \"The Nordiques\" originiate from?", answer: "Quebec City")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "What year did the New Orleans Saints win the Super Bowl?", answer: "2010")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "What team did England beat to win in the 1966 World Cup final?", answer: "West Germany")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "Who won the premier league title in the 2015-2016 season following a fairy tale run?", answer: "Leicester City")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "The Los Angeles Dodgers were originally from what U.S. city?", answer: "Brooklyn")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "Who won the 2017 Formula One World Drivers' Championship?", answer: "Lewis Hamilton")
  Card.find_or_create_by!(category: sports, cardset: easy_difficulty, question: "Who won the UEFA Champions League in 2016?", answer: "Real Madrid C.F.")

  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "The body of the Egyptian Sphinx was based on which animal?", answer: "Lion")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Which country does Austria not border?", answer: "France")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "What is the only state in the United States that does not have a flag in a shape with 4 edges?", answer: "Ohio")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Which of the following languages does NOT use the Latin alphabet?", answer: "Georgian")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Which nation claims ownership of Antarctica?", answer: "No one, but there are claims.")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "How many countries does the United States share a land border with?", answer: "2")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Harvard University is located in which city?", answer: "Cambridge")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Which of the following Japanese islands is the biggest?", answer: "Honshu")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Which of the following countries has a flag featuring a yellow lion wielding a sword on a dark red background?", answer: "Sri Lanka")
  Card.find_or_create_by!(category: geography, cardset: easy_difficulty, question: "Which country was NOT part of the Soviet Union?", answer: "Romania")

  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "King Henry VIII was the second monarch of which European royal house?", answer: "Tudor")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "The idea of Socialism was articulated and advanced by whom?", answer: "Karl Marx")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "Which one of these tanks was designed and operated by the United Kingdom?", answer: "Tog II")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "During WWII, in 1945, the United States dropped atomic bombs on the two Japanese cities of Hiroshima and what other city?", answer: "Nagasaki")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "Which of these countries remained neutral during World War II?", answer: "Switzerland")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "Which modern day country is the region that was known as Phrygia in ancient times?", answer: "Turkey")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "Who was the first president of the United States?", answer: "George Washington")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "What year did World War I begin?", answer: "1914")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "Which of the following was Brazil was a former colony under?", answer: "Portugal")
  Card.find_or_create_by!(category: history, cardset: easy_difficulty, question: "What was the name commonly given to the ancient trade routes that connected the East and West of Eurasia?", answer: "Silk Road")



  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What is the fastest  land animal?", answer: "Cheetah")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What is the scientific name for modern day humans?", answer: "Homo Sapiens")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "The Kākāpō is a large, flightless, nocturnal parrot native to which country?", answer: "New Zealand")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "Hippocampus is the Latin name for which marine creature?", answer: "Seahorse")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What do you call a baby bat?", answer: "Pup")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What is Grumpy Cat's real name?", answer: "Tardar Sauce")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "Which class of animals are newts members of?", answer: "Amphibian")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What is the collective noun for a group of crows?", answer: "Murder")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What colour is the female blackbird?", answer: "Brown")
  Card.find_or_create_by!(category: animals, cardset: easy_difficulty, question: "What is the name of a rabbit's abode?", answer: "Burrow")

  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "The Italian automaker Lamborghini uses what animal as its logo?", answer: "Bull")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "Which Italian city is home of the car manufacturer 'Fiat'?", answer: "Turin")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "Which of the following car manufacturers had a war named after it?", answer: "Toyota")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "Jaguar Cars was previously owned by which car manfacturer?", answer: "Ford")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "What UK Train does NOT go over 125MPH?", answer: "Sprinter")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "Automobiles produced by Telsa Motors operate on which form of energy?", answer: "Electricity")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "Which car tire manufacturer is famous for its \"P Zero\" line?", answer: "Pirelli")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "What are the cylinder-like parts that pump up and down within the engine?", answer: "Pistons")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "What country was the Trabant 601 manufactured in?", answer: "East Germany")
  Card.find_or_create_by!(category: vehicles, cardset: easy_difficulty, question: "What is the fastest road legal car in the world?", answer: "Koenigsegg Agera RS")

  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "What does the \"G\" mean in \"G-Man\"?", answer: "Government")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "Which language is NOT Indo-European?", answer: "Hungarian")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "What did the Spanish autonomous community of Catalonia ban in 2010, that took effect in 2012?", answer: "Bullfighting")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "What was the soft drink Pepsi originally introduced as?", answer: "Brad's Drink")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "Where does water from Poland Spring water bottles come from?", answer: "Maine, United States")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "The website \"Shut Up & Sit Down\" reviews which form of media?", answer: "Board Games")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "Which country has the most Trappist breweries?", answer: "Belgium")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "What is the highest number of Michelin stars a restaurant can receive?", answer: "Three")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "What is the full title of the Prime Minister of the UK?", answer: "First Lord of the Treasury")
  Card.find_or_create_by!(category: general_knowledge, cardset: moderate_difficulty, question: "The Mexican Beer \"Corona\" is what type of beer?", answer: "Pale Lager")

  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "Which of the following authors was not born in England? ", answer: "Arthur Conan Doyle")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "How many books are in the Chronicles of Narnia series?", answer: "7")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "The novel \"Of Mice And Men\" was written by what author? ", answer: "John Steinbeck ")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "J.K. Rowling completed \"Harry Potter and the Deathly Hallows\" in which hotel in Edinburgh, Scotland?", answer: "The Balmoral")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "Which American author was also a budding travel writer and wrote of his adventures with his dog Charley?", answer: "John Steinbeck")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "The book \"The Little Prince\" was written by...", answer: "Antoine de Saint-Exup&eacute;ry")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "In Michael Crichton's novel \"Jurassic Park\", John Hammond meets his demise at the claws of which dinosaur?", answer: "Procompsognathus")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "In the \"Harry Potter\" novels, what must a Hogwarts student do to enter the Ravenclaw Common Room?", answer: "Answer a riddle")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "What is the name of the gang that Ponyboy is a part of in the book, The Outsiders?", answer: "The Greasers")
  Card.find_or_create_by!(category: entertainment_books, cardset: moderate_difficulty, question: "In Alice in Wonderland, what is the name of Alice's kitten?", answer: "Dinah")

  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "Which 1958 movie starred Kirk Douglas and Tony Curtis as half-brothers Einar and Eric?", answer: "The Vikings ")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "Which retired American football quarterback played himself in 'Ace Ventura: Pet Detective' and 'Little Nicky'?", answer: "Dan Marino")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "Who voiced the character Draco in the 1996 movie 'DragonHeart'?", answer: "Sean Connery")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "In which African country was the 2006 film 'Blood Diamond' mostly set in?", answer: "Sierra Leone")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "Who plays the Nemesis in the Resident Evil movies?", answer: "Matthew Taylor")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "In Back to the Future Part II, Marty and Dr. Emmett Brown go to which future date?", answer: "October 21, 2015")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "In the 1999 movie Fight Club, which of these is not a rule of the \"fight club\"?", answer: "Always wear a shirt")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "What year did the James Cameron film \"Titanic\" come out in theaters?", answer: "1997")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "Which actor plays the character \"Tommy Jarvis\" in \"Friday the 13th: The Final Chapter\" (1984)?", answer: "Corey Feldman")
  Card.find_or_create_by!(category: entertainment_film, cardset: moderate_difficulty, question: "Who did the score to the original Blade Runner?", answer: "Vangelis")

  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "According to a Beatles song, who kept her face in a jar by the door?", answer: "Eleanor Rigby")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "Which of these artists was NOT a member of the electronic music supergroup Swedish House Mafia, which split up in 2013?", answer: "Alesso")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "EDM record label Monstercat is based in which country?", answer: "Canada")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "Which of these artists has NOT been a member of dancehall group Major Lazer?", answer: "Skrillex")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "Which song in Drake's \"Views\" features Future?", answer: "Grammys")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "When did Tame Impala release their second album?", answer: "2012")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "Which rapper had an album that went double platinum with no features?", answer: "J. Cole")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "Which of these songs is not on the \"untitled\" album by Led Zeppelin?", answer: "Celebration Day")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "What was David Bowie's real surname?", answer: "Jones")
  Card.find_or_create_by!(category: entertainment_music, cardset: moderate_difficulty, question: "Moby, an American DJ, singer, and musician, achieved worldwide success for the 1999 release of which of the following albums?", answer: "Play")

  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "What year did the television company BBC officially launch the channel BBC One?", answer: "1936")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "Which track by \"Massive Attack\" is used for the theme of \"House\"? ", answer: "Teardrop")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "Who was the star of the TV series \"24\"?", answer: "Kiefer Sutherland")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "What was the name of Ross' pet monkey on \"Friends\"?", answer: "Marcel")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "What is the name of the \"Flash\" and \"Arrow\" spinoff featuring a team of characters that have appeared on both shows?", answer: "Legends of Tomorrow")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "How many seasons did the TV show \"Donkey Kong Country\" last?", answer: "2")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "Which WWF wrestler had the nickname \"The Ayatollah of Rock 'N' Rolla\"?", answer: "Chris Jericho")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "Cesar Romero played which iconic Batman villain from the 1960's TV show?", answer: "The Joker")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "In Game of Thrones what is the name of Jon Snow's sword?", answer: "Longclaw")
  Card.find_or_create_by!(category: entertainment_television, cardset: moderate_difficulty, question: "What actor portrays Hogan \"Wash\" Washburne in the TV Show Firefly?", answer: "Alan Tudyk")

  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "What was the first living creature in space?", answer: "Fruit Flies ")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "Au on the Periodic Table refers to which element?", answer: "Gold")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "Which one of these scientists conducted the Gold Foil Experiment which concluded that atoms are mostly made of empty space?", answer: "Ernest Rutherford")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "Which of these is a type of stretch/deep tendon reflex?", answer: "Ankle jerk reflex")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "Myopia is the scientific term for which condition?", answer: "Shortsightedness")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "Deuterium is an isotope of which element?", answer: "Hydrogen")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "In Psychology, which need appears highest in the \"Maslow's hierarchy of needs\" pyramid?", answer: "Esteem")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "What are human nails made of?", answer: "Keratin")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "What part of the brain takes its name from the Greek for seahorse?", answer: "Hippocampus")
  Card.find_or_create_by!(category: science_nature, cardset: moderate_difficulty, question: "Which planet did the \"Viking 1\" spacecraft send surface images of, starting in 1976?", answer: "Mars")

  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "This Greek mythological figure is the god/goddess of battle strategy (among other things).", answer: "Athena")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "The Hippogriff, not to be confused with the Griffon, is a magical creature with the front half of an eagle, and the back half of what?", answer: "A Horse")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "Which of the following Mesopotamian mythological figures was NOT a deity?", answer: "Enkidu")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "Which of these Roman gods doesn't have a counterpart in Greek mythology?", answer: "Janus")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "A minotaur is half human half what?", answer: "Bull")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "In African mythology, Anansi is a trickster and storyteller who takes the shape of which animal?", answer: "Spider")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "The Maori hold that which island nation was founded by Kupe, who discovered it under a long white cloud?", answer: "New Zealand")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "What is the name of the first human being in Norse mythology?", answer: "Ask")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "Hel was the daughter of which Norse Mythological figure?", answer: "Loki")
  Card.find_or_create_by!(category: mythology, cardset: moderate_difficulty, question: "What animal did Queen Pasipahe sleep with before she gave birth to the Minotaur in Greek Mythology?", answer: "Bull")

  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "What cricketing term denotes a batsman being dismissed with a score of zero?", answer: "Duck")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "Which of these teams isn't a member of the NHL's \"Original Six\" era?", answer: "Philadelphia Flyers")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "In a game of snooker, what colour ball is worth 3 points?", answer: "Green")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "Which soccer team won the Copa Am&eacute;rica Centenario 2016?", answer: "Chile")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "What is the oldest team in Major League Baseball?", answer: "Atlanta Braves")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "In Formula 1, the Virtual Safety Car was introduced following the fatal crash of which driver?", answer: "Jules Bianchi")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "Which portuguese island is soccer player Cristiano Ronaldo from?", answer: "Madeira")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "Who won the 2015 College Football Playoff (CFP) National Championship? ", answer: "Ohio State Buckeyes")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "Which of these countries' national teams qualified for the 2018 FIFA World Cup in Russia?", answer: "Tunisia")
  Card.find_or_create_by!(category: sports, cardset: moderate_difficulty, question: "Who won the 2018 Monaco Grand Prix?", answer: "Daniel Ricciardo")

  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "How many sovereign states are members of the United Nations?", answer: "195")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "What is the name of the former country that was succeeded by countries such as Serbia, Croatia and Slovenia?", answer: "Yugoslavia")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "Which is the largest city in Morocco?", answer: "Casablanca")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "The World Health Organization headquarters is located in which European country?", answer: "Switzerland")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "How many countries are larger than Australia?", answer: "5")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "Where are the Nazca Lines located?", answer: "Peru")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "Which country has three capital cities?", answer: "South Africa")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "What is the highest mountain in the world?", answer: "Mt. Everest")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "How many countries share a land border with Luxembourg?", answer: "3")
  Card.find_or_create_by!(category: geography, cardset: moderate_difficulty, question: "Frankenmuth, a US city nicknamed \"Little Bavaria\", is located in what state?", answer: "Michigan")

  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "In relation to the British Occupation in Ireland, what does the IRA stand for.", answer: "Irish Republican Army")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "When did Jamaica recieve its independence from England? ", answer: "1962")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "All of the following are names of the Seven Warring States EXCEPT:", answer: "Zhai (翟)")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "What year did the Battle of Agincourt take place?", answer: "1415")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "In which years did the Battle of Gallipoli take place?", answer: "1915 - 1916")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "In what year did Kentucky become the 15th state to join the union?", answer: "1792")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "In what year did the Berlin Wall fall?", answer: "1989")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "Who crowned Charlemagne as Holy Roman Emperor on Christmas Day in 800?", answer: "Pope Leo III")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "The Thirty Years War ended with which treaty?", answer: "Peace of Westphalia")
  Card.find_or_create_by!(category: history, cardset: moderate_difficulty, question: "After his loss at the Battle of Waterloo, Napoleon Bonaparte was exiled to which island?", answer: "St. Helena")

  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Who was the British Prime Minister at the outbreak of the Second World War?", answer: "Neville Chamberlain")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Which president erased the national debt of the United States?", answer: "Andrew Jackson")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Who was the only president to not be in office in Washington D.C?", answer: "George Washington")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Who was the 40th President of the USA?", answer: "Ronald Reagan")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Before 2011, \"True Capitalist Radio\" was known by a different name. What was that name?", answer: "True Conservative Radio")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "The 2014 movie \"The Raid 2: Berandal\" was mainly filmed in which Asian country?", answer: "Indonesia")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "In United States history, how many vice presidents did Franklin D. Roosevelt have during his time in office as president?", answer: "3")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Who succeeded Joseph Stalin as General Secretary of the Communist Party of the Soviet Union?", answer: "Nikita Khrushchev")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "The Watergate Scandal occured in what year?", answer: "1972")
  Card.find_or_create_by!(category: politics, cardset: moderate_difficulty, question: "Between 1973 to 1990, what country was ruled by dictator Augusto Pinochet?", answer: "Chile")


  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What does \"hippopotamus\" mean and in what langauge?", answer: "River Horse (Greek)")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What type of animal is a natterjack?", answer: "Toad")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "Cashmere is the wool from which kind of animal?", answer: "Goat")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What is the scientific name for the \"Polar Bear\"?", answer: "Ursus Maritimus")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What are rhino's horn made of?", answer: "Keratin")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "The now extinct species \"Thylacine\" was native to where?", answer: "Tasmania, Australia")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "Which of these species is not extinct?", answer: "Komodo dragon")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What dog bread is one of the oldest breeds of dog and has flourished since before 400 BCE.", answer: "Pugs")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What is the scientific name of the Common Chimpanzee?", answer: "Pan troglodytes")
  Card.find_or_create_by!(category: animals, cardset: moderate_difficulty, question: "What is the collective noun for rats?", answer: "Mischief")

  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Which country has the international vehicle registration letter 'A'?", answer: "Austria")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Which of the following is NOT a Russian car manufacturer?", answer: "BYD")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Which of the following passenger jets is the longest?", answer: "Boeing 747-8")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Complete the following analogy: Audi is to Volkswagen as Infiniti is to ?", answer: "Nissan")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Which of the following car models has been badge-engineered (rebadged) the most?", answer: "Isuzu Trooper")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Volkswagen's legendary VR6 engine has cylinders positioned at what degree angle?", answer: "15 Degree")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "When was Cadillac founded?", answer: "1902")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Which one of the following is not made by Ford?", answer: "Camry")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "What nickname was given to Air Canada Flight 143 after it ran out of fuel and glided to safety in 1983?", answer: "Gimli Glider")
  Card.find_or_create_by!(category: vehicles, cardset: moderate_difficulty, question: "Which of these cars is NOT considered one of the 5 Modern Supercars by Ferrari?", answer: "Testarossa")

  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "The words \"bungalow\" and \"shampoo\" originate from the languages of which country?", answer: "India")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "When was \"YouTube\" founded?", answer: "February 14, 2005")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "Before the 19th Century, the \"Living Room\" was originally called the...", answer: "Parlor")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "Which film star has his statue in Leicester Square?", answer: "Charlie Chaplin")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "Sciophobia is the fear of what?", answer: "Shadows")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "Which of these banks are NOT authorized to issue currency notes in Hong Kong?", answer: "OCBC")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "According to the 2014-2015 Australian Bureau of Statistics, what percentage of Australians were born overseas?", answer: "28%")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "Which church's interior in Vatican City was designed in 1503 by renaissance architects including Bramante, Michelangelo and Bernini?", answer: "St. Peter's Basilica")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "The word \"aprosexia\" means which of the following?", answer: "The inability to concentrate on anything")
  Card.find_or_create_by!(category: general_knowledge, cardset: hard_difficulty, question: "Which of these cities does NOT have a United States Minting location?", answer: "St. Louis, MO")

  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "In the Beatrix Potter books, what type of animal is Tommy Brock?", answer: "Badger")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "Who wrote the novel \"Moby-Dick\"?", answer: "Herman Melville")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "In the Harry Potter universe, what is Cornelius Fudge's middle name?", answer: "Oswald")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "Which of these does Charlie NOT read in The Perks of Being a Wallflower?", answer: "The Grapes of Wrath")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "Where does the book \"The Silence of the Lambs\" get its title from?", answer: "The main character's trauma in childhood")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "In the book series \"Odd Thomas\", Danny Jessup has what genetic disease? ", answer: " Osteogenesis Imperfecta")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "In Margaret Atwood's \"The Handmaid's Tale\", what is Offred's real name is implied to be?", answer: "June")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "In the Magic: The Gathering universe, which plane does the Homelands expansion take place in?", answer: "Ulgrotha")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "In which classic novel is there a character named Homer Simpson?", answer: "The Day of the Locust")
  Card.find_or_create_by!(category: entertainment_books, cardset: hard_difficulty, question: "Which author co-wrote \"The Communist Manifesto\" alongside Karl Marx?", answer: "Friedrich Engels")

  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "In the 1964 film \"Zulu\", what song does the British Army company sing before the final battle?", answer: "Men of Harlech")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "What was the first movie to ever use a Wilhelm Scream?", answer: "Distant Drums")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "In the movie \"Scream\" who is Ghost Face?", answer: "Billy Loomis and Stu Macher")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "According to \"Star Wars\" lore, which planet does Obi-Wan Kenobi come from?", answer: "Stewjon")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "Before \"Jurassic Park III\" was finalized and the Spinosaurus was chosen, which dinosaur was going to be the star?", answer: "Baryonyx")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "Which actress portrayed Dr. Grace Augustine in the James Cameron movie \"Avatar\"?", answer: "Sigourney Weaver")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "In Big Hero 6, what were Baymax's motions modeled after?", answer: "Baby penguins")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "Which boxer was famous for striking the gong in the introduction to J. Arthur Rank films?", answer: "Bombardier Billy Wells")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "What was Humphrey Bogart's middle name?", answer: "DeForest")
  Card.find_or_create_by!(category: entertainment_film, cardset: hard_difficulty, question: "In the film \"Harry Potter and the Order of The Phoenix\", why was Harry Potter's scream, after Sirius Black died, muted?", answer: "Too Agonizing")

  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "What was the last Aphex Twin album released before his decade-long hiatus?", answer: "Drukqs")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "Who was the original drummer for The Beatles?", answer: "Tommy Moore")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "Who had a 1981 hit with the song \"Japanese Boy\"?", answer: "Aneka")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "The key of sharps does the key of G# minor contain?", answer: "5")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "This album, now considered to be one of the greatest of all time, was a commercial failure when it was released.", answer: "The Velvet Underground and Nico")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "Who designed the album cover for True Romance, an album by Estelle?", answer: "Rebecca Sugar")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "In the Panic! At the Disco's song \"Nothern Downpour\", which lyric follows 'I know the world's a broken bone'.", answer: "\"So melt your headaches call it home\"")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "What was the name of the cold-war singer who has a song in Grand Theft Auto IV, and a wall landmark in Moscow for his memorial?", answer: "Viktor Tsoi")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "Artis Leon Ivey Jr. is better known as which rap artist?", answer: "Coolio")
  Card.find_or_create_by!(category: entertainment_music, cardset: hard_difficulty, question: "Where was Nicki Minaj born?", answer: "Trinidad and Tobago")

  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "What's Dr. Doofenshmirtz first name?", answer: "Heinz")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "Which country does the YouTuber \"SinowBeats\" originate from?", answer: "Scotland")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "Who played the sun baby in the original run of Teletubbies?", answer: "Jessica Smith")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "What is the Klingon's afterlife called?", answer: "Sto-vo-kor")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "In \"Star Trek\", who was the founder of the Klingon Empire and its philosophy?", answer: "Kahless the Unforgettable")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "In 2008, British celebrity chef Gordon Ramsay believes he almost died after suffering what accident in Iceland while filming?", answer: "Slipping off a cliff, and nearly drowning in icy water")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "What was the name of the inflatable duck sacrified to the crowd at the end of Episode 34 of the 18th season of Big Brother?", answer: "Pablo")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "Which of these Nickelodeon game shows aired first?", answer: "Double Dare")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "What was the UK \"Who Wants to be a Millionaire?\" cheating scandal known as?", answer: "Major Fraud")
  Card.find_or_create_by!(category: entertainment_television, cardset: hard_difficulty, question: "What was the date of original airing of the pilot episode of My Little Pony: Friendship is Magic?", answer: "October 10th, 2010")

  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "What common name is given to the medial condition, tibial stress syndrome (MTSS)?", answer: "Shin Splints")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "If you planted the seeds of Quercus robur what would grow?", answer: "Trees")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "Folic acid is the synthetic form of which vitamin?", answer: "Vitamin B")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "\"The Big Bang Theory\" was first theorized by a priest of what religious ideology?", answer: "Catholic")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "Which of these is a stop codon in DNA?", answer: "TAA")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "Which of the following plastic is commonly used for window frames, gutters and drain pipes?", answer: "Polyvinylchloride (PVC) ")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "What nucleotide pairs with guanine?", answer: "Cytosine")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "What is the scientific name for the extinct hominin known as \"Lucy\"?", answer: "Australopithecus Afarensis")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "What is the name for the auditory illusion of a note that seems to be rising infinitely?", answer: "Shepard Tone")
  Card.find_or_create_by!(category: science_nature, cardset: hard_difficulty, question: "Which of the following is considered classical conditioning?", answer: "Pavlov's dog experiments")

  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "Talos, the mythical giant bronze man, was the protector of which island?", answer: "Crete")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "What was the punishment for Sysiphus's craftiness?", answer: "Cursed to roll a boulder up a hill for eternity.")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "According to Algonquian folklore, how does one transform into a Wendigo?", answer: "Participating in cannibalism.")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "In Greek Mythology, who was the daughter of King Minos?", answer: "Ariadne")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "In Norse mythology, what is the name of the serpent which eats the roots of the ash tree Yggdrasil?", answer: "Nidhogg")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "Which of the following is NOT a god in Norse Mythology.", answer: "Jens")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "Nidhogg is a mythical creature from what mythology?", answer: "Norse")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "Who is the Egyptian god of reproduction and lettuce?", answer: "Min")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "What immense structure is referred to in Norse Mythology as the Yggdrasil.", answer: "Tree")
  Card.find_or_create_by!(category: mythology, cardset: hard_difficulty, question: "Which Norse God has a horse named Sleipnir?", answer: "Odin")

  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "How many times did Martina Navratilova win the Wimbledon Singles Championship?", answer: "Nine")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "With which doubles partner did John McEnroe have most success?", answer: "Peter Fleming")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "Which male player won the gold medal of table tennis singles in 2016 Olympics Games?", answer: "Ma Long (China)")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "Which female player won the gold medal of table tennis singles in 2016 Olympics Games?", answer: "DING Ning (China)")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "What is the full name of the footballer \"Cristiano Ronaldo\"?", answer: "Cristiano Ronaldo dos Santos Aveiro")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "Which year was the third Super Bowl held?", answer: "1969")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "Which city features all of their professional sports teams' jersey's with the same color scheme?", answer: "Pittsburgh")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "Who is Manchester United's leading appearance maker?", answer: "Ryan Giggs")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "The Mazda 787B won the 24 Hours of Le Mans in what year?", answer: "1991")
  Card.find_or_create_by!(category: sports, cardset: hard_difficulty, question: "What is &ldquo;The Sport of Kings&rdquo;?", answer: "Horse Racing")

  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "What country is not a part of Scandinavia?", answer: "Finland")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "What is the largest city and commercial capital of Sri Lanka?", answer: "Colombo")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "Which of these is NOT a province in China?", answer: "Yangtze")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "Where is the Luxor Hotel & Casino located?", answer: "Paradise, Nevada")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "What North American tourist attraction is served by the \"Maid of the Mist\" tour company?", answer: "Niagara Falls")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "What is the tallest mountain in Canada?", answer: "Mount Logan")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "When does Finland celebrate their independence day?", answer: "December 6th")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "The Andaman and Nicobar Islands in South East Asia are controlled by which country?", answer: "India")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "How many stations does the Central Line have on the London Underground?", answer: "49")
  Card.find_or_create_by!(category: geography, cardset: hard_difficulty, question: "The Maluku islands (informally known as the Spice Islands) belong to which country?", answer: "Indonesia")

  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "Spain was formed in 1469 with the marriage of Isabella I of Castile and Ferdinand II of what other Iberian kingdom?", answer: "Aragon")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "What was the name of the spy ring that helped the United States win the Revolutionary War?", answer: "Culper Ring")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "What did the first vending machines in the early 1880's dispense?", answer: "Post cards")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "During the Roman Triumvirate of 42 BCE, what region of the Roman Republic was given to Lepidus?", answer: "Hispania ")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "In which year did the Tokyo Subway Sarin Attack occur?", answer: "1995")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "During the Spanish Civil War (1936), Francisco Franco fought for which political faction?", answer: "Nationalist Spain")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "What was the name of the German offensive operation in October 1941 to take Moscow before winter?", answer: "Operation Typhoon")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "From 1940 to 1942, what was the capital-in-exile of Free France ?", answer: "Brazzaville")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "The coat of arms of the King of Spain contains the arms from the monarchs of Castille, Leon, Aragon and which other former Iberian kingdom?", answer: "Navarre")
  Card.find_or_create_by!(category: history, cardset: hard_difficulty, question: "Which of the following physicists did NOT work on the Manhattan project?", answer: "Murray Gell-Mann")

  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "Which Native American tribe/nation requires at least one half blood quantum (equivalent to one parent) to be eligible for membership?", answer: "Yomba Shoshone Tribe")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "Which letter do you need to have on a European driver license in order to ride any motorbikes?", answer: "A")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "\"Yes, America Can!\" was this United States politician's de facto campaign slogan in 2004.", answer: "George W. Bush")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "Which of the following United States Presidents served the shortest term in office?", answer: "William Henry Harrison")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "What is the name of Niccol&ograve; Machiavelli's work that argued effective leaders needed to crush their opponents at all costs?", answer: "The Prince")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "What is centralism?", answer: " Concentration of power and authority in a central organization.")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "Which of these was an official candidate in the 2017 British General Election?", answer: "Lord Buckethead")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "In June 2017, Saudi Arabia and Egypt broke off ties with which country over its supposed support for terrorism?", answer: "Qatar")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "Who was the longest-serving senator in US history, serving from 1959 to 2010?", answer: "Robert Byrd")
  Card.find_or_create_by!(category: politics, cardset: hard_difficulty, question: "What year did the effort to deploy the Common Core State Standards (CCSS) in the US begin?", answer: "2009")


  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "What scientific family does the Aardwolf belong to?", answer: "Hyaenidae")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "What is the scientific name of the cheetah?", answer: "Acinonyx jubatus")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "What type of creature is a Bonobo?", answer: "Ape")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "Unlike on most salamanders, this part of a newt is flat?", answer: "Tail")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "What is the name of the copper-rich protein that creates the blue blood in the Antarctic octopus?", answer: "Hemocyanin")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "Which species is a \"mountain chicken\"?", answer: "Frog")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "Which of the following is another name for the \"Poecilotheria Metallica Tarantula\"?", answer: "Gooty")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "Which of these is a colony of polyps and not a jellyfish?", answer: "Portuguese Man-of-War")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "What is the collective noun for vultures?", answer: "Wake")
  Card.find_or_create_by!(category: animals, cardset: hard_difficulty, question: "What bird is born with claws on its wing digits?", answer: "Hoatzin")

  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "What was the name of the first front-wheel-drive car produced by Datsun (now Nissan)?", answer: "Cherry")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "The difference between the lengths of a Boeing 777-300ER and an Airbus A350-1000 is closest to:", answer: "0.1m")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "Which car is the first mass-produced hybrid vehicle?", answer: "Toyota Prius")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "Which Variable Valve Timing technology is used by BMW?", answer: "VANOS")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "What engine is in the Lexus SC400?", answer: "1UZ-FE")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "Which one of the following is NOT a sub-company of the Volkswagen Group?", answer: "Opel")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "In 2014, over 6 million General Motors vehicles were recalled due to what critical flaw?", answer: "Faulty ignition switch")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "Which Audi does not use Haldex based all wheel drive system?", answer: "Audi A8")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "What year did the Chevrolet LUV mini truck make its debut?", answer: "1972")
  Card.find_or_create_by!(category: vehicles, cardset: hard_difficulty, question: "What kind of train was Stepney, a train on the Bluebell Railway notable for his appearance in \"The Railway Series\"?", answer: "LB&SCR A1X")
end
