# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6dbca38a089022d839b8d62c804d1dd0d66b8de8f732e81e49187867cf5e5d71ca90a6ae243ca08f7ac99ed6876dbe4edeebadaeca0a142c8efec0623ef8740f

test:
  secret_key_base: 47932782a64f7f17b1ff5be60a07aa8408ab69148bf599014aadddd124e2f87d7184598e3553c0a7b152d41a3aef627e52f676388ef6128bfa855bed474786dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
